#!/bin/bash
TABLES=$(mdb-tables -1 $1)
TABLES=`echo "$TABLES" | sed -e "s/Palabras.vac.as/PalabrasVacias/"`

for t in $TABLES
do
	echo "DROP TABLE IF EXISTS \"$t\";"
done

mdb-schema $1 mysql

for t in $TABLES
do
	if [ "PalabrasVacias" == "$t" ]
	then
		t="Palabras Vacías"
	fi
	mdb-export -D "%Y-%m-%d %H:%M:%S" -I mysql $1 "$t"
done
