#!/bin/sh
# Workaround for VIM ALE: https://github.com/dense-analysis/ale/issues/2427

if [ ! -e "./vendor/bin/phpcbf" ];
then
	exit
fi

out=$(printf "%s" "$(phpcbf -q $@)")
if [ "$( echo \"$out\" | grep 'No fixable' )" ];
then
	exit
fi
if [ "$( echo \"$out\" | grep 'Warning: ' )" ];
then
	exit
fi

printf "%s" "$out"
