#!/bin/bash

SRC=`dirname $0`

if [ $# -lt 1 ];
then
	echo "Missing skel name."
	echo "Usage: skel [SKEL] [TARGET_FOLDER]"
	exit 1
fi

if [ $# -lt 2 ];
then
	echo "Missing skel name."
	echo "Usage: skel [SKEL] [TARGET_FOLDER]"
	exit 1
fi


name="$1"
folder="$2"

if [ -e "$folder" ];
then
	echo "'$folder' already exists."
	exit 1
else
	mkdir -p "$folder"
fi

cp -r "$SRC"/skels/$name/* "$folder"
