# Clipboard
bindd = SUPER, C, Clipboard history, exec, omarchy launch walker -m clipboard
bindd = SUPER SHIFT, C, Calculator, exec, omarchy launch walker -m calc

# Menus
bindd = SUPER, M, Launch apps, exec, omarchy launch walker -p "Launch…"
bindd = SUPER, APOSTROPHE, Emoji picker, exec, omarchy launch walker -m symbols
bindd = SUPER, A, Omarchy menu, exec, omarchy menu
bindd = SUPER, ESCAPE, Power menu, exec, omarchy menu system
bindd = SUPER SHIFT, SLASH, , exec, omarchy menu keybindings

# Toggle nightlight
bindd = SUPER, N, Toggle nightlight, exec, omarchy toggle nightlight

# Screenshots
bindd = SUPER, P, Screenshot of region, exec, omarchy capture screenshot
bindd = SUPER SHIFT, P, Screenshot of display, exec, omarchy capture screenshot fullscreen

# Screen recordings
bindd = SUPER, V, Screen record a region, exec, omarchy capture screenrecording

# Color picker
bindd = SUPER, D, Dropper tool (color picker), exec, pkill hyprpicker || hyprpicker -a
