" Basics {{{
filetype plugin indent on
syntax on
" }}}

" Settings {{{
set backspace=indent,eol,start      " Prefer backspace to cover several files
set backupdir=/tmp                  " Location of swap files
set cursorline                      " Highlight current line
set encoding=utf-8                  " Fix encoding
set hidden                          " Prefer hiding over unloading buffers
set hlsearch                        " Highlight search
set list                            " Show invisible characters
set listchars=tab:▸\ ,eol:¬ ",space:· " Invisible characters
set nocursorline                    " Don't highlight current line
set path=.,**/*                     " Search relative to current file + directory
set shiftwidth=2                    " Indentation defaults (<< / >> / == / auto)
set splitbelow                      " Prefer new horizontal split below
set splitright                      " Prefer new vertical split to the right
set tabstop=2                       " Tab characters take two spaces only
set undolevels=100                  " Number of undo levels
set wildignore+=.svn,.git,node_modules,*.o,*.a,*.class,*.mo,*.la,*.so,*.obj,*.swp,*.jpg,*.png,*.xpm,*.gif,*.pdf,*.bak,*.beam,*.pyc,*.min.css,*.min.js
" }}}

" UI {{{
silent! colorscheme hybrid
silent! set background=dark
let g:airline_theme='hybrid'
let g:netrw_dirhistmax = 0
" }}}

" EasyAlign {{{
xmap ga <Plug>(EasyAlign)
nmap ga <Plug>(EasyAlign)
" }}}

" ALE {{{
highlight ALEErrorSign ctermbg=NONE ctermfg=red
highlight ALEWarningSign ctermbg=NONE ctermfg=yellow
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_sign_error = '>>'
let g:ale_sign_warning = '> '
let g:ale_fixers = { '*': [ 'remove_trailing_lines', 'trim_whitespace' ] }
let g:ale_php_phpcbf_executable = $HOME . '/.bin/phpcbf-vim'
let g:ale_php_phpcbf_use_global = 1
" }}}


vnoremap <leader>a :%j<CR>:s/<\/\?p>//g<CR>I<p><ESC>A</p><ESC>:let @/ = "mark"<CR>
