source = ~/.config/hypr/bindings/apps.conf
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new
source = ~/.config/hypr/bindings/tiling.conf
source = ~/.config/hypr/bindings/utilities.conf
