-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here


-- local formatters = require 'lvim.lsp.null-ls.formatters'
-- formatters.setup({
-- 	{
-- 		name = 'phpcbf',
-- 		command = '~/.config/composer/vendor/bin/phpcbf',
-- 		args = { '-q', '--stdin-path=$FILENAME', getPhpcbfStandard(), '-' }
-- 	},
-- 	{
-- 		name = 'prettier',
-- 		filetypes = { 'javascript', 'json', 'typescript', 'typescriptreact', 'css', 'scss' },
-- 	},
-- 	{
-- 		name = 'stylelint',
-- 		command = 'stylelint --fix',
-- 		filetypes = { 'css', 'scss' },
-- 	}
-- })
--
-- local linters = require 'lvim.lsp.null-ls.linters'
-- linters.setup({
-- 	{
-- 		name = 'eslint_d',
-- 		filetypes = { 'javascript', 'typescript', 'typescriptreact' },
-- 	},
-- 	{
-- 		name = 'stylelint',
-- 		filetypes = { 'css', 'scss' },
-- 	},
-- })
